### ISSUE TITLE
About SQLite FTS5 and offsets

### ISSUE THREAD

**Issue by edwinyzh** [nalgeon/sqlite-plus#1]
Hello Anton,

Just read your article about SQLite is not a toy database and found that comments were not enabled, and I'm wondering if I can take this chance to ask do you happen to know how to implement the `offsets` function for FTS5?

Thanks!

**Comment by nalgeon** [comment]
Hello Edwin! What's an `offsets` function, could you give an example?

**Comment by edwinyzh** [comment]
Anton,

It's the official [`offsets` functions supported by FTS3/4](https://sqlite.org/fts3.html#offsets) but not supported by [FTS5](https://sqlite.org/fts5.html#_auxiliary_function_changes_).

**Comment by nalgeon** [comment]
Quoting from [FTS5 docs](https://sqlite.org/fts5.html):

> FTS5 has no matchinfo() or offsets() function, and the snippet() function is not as fully-featured as in FTS3/4. However, since FTS5 does provide an API allowing applications to create custom auxiliary functions, any required functionality may be implemented within the application code.

I never worked with custom auxiliary functions, so I've got no idea how to implement `offsets()` 🤷

**Comment by edwinyzh** [comment]
No problem and I'm await your next awesome article on SQLite :)

**Comment by nalgeon** [comment]
Thank you very much, Edwin! Will do my best ツ
