### ISSUE TITLE
Add regexp extension to this great project

### ISSUE THREAD

**Issue by aborruso** [nalgeon/sqlite-plus#3]
Hi,
first of all thank you, this is a great repo, a great idea.

What about to add the REGEXP extension you have here:
https://www.sqlite.org/src/dir?ci=tip&name=ext/misc

Best regards

**Comment by nalgeon** [comment]
Hello Andrea! Thanks a lot! I'm already working on the regexp extension ツ Will notify you as soon as it's ready.

**Comment by nalgeon** [comment]
Not exactly, I'm afraid. It fails with segmentation fault on certain circumstances, I'm investigating the issue.

**Comment by nalgeon** [comment]
Found the root cause, planning to fix it in a couple of days.

**Comment by nalgeon** [comment]
Fixed in [0.3.1](https://github.com/nalgeon/sqlite-plus/releases/tag/0.3.1) 🥳

**Comment by aborruso** [comment]
Thank you very much

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il mer 31 mar 2021, 13:45 Anton Zhiyanov ***@***.***> ha
scritto:
